name: Metrics
on:
  schedule:
    - cron: "0 */6 * * *" # Update every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: arga-nata
          template: classic
          base: "" 
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_limit: 5
          config_timezone: "Asia/Jakarta"
          committer_branch: metrics # SIMPAN KE BRANCH METRICS
