name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_METRICS_TOKEN }}
          user: arga-nata
          template: ""
          base: ""
          filename: wakatime.svg
          committer_branch: metrics
          committer_message: "Update WakaTime metrics"
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_limit: 5
          config_timezone: Asia/Jakarta

      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_METRICS_TOKEN }}
          user: arga-nata
          filename: metrics.svg
          committer_branch: metrics
          committer_message: "Update activity metrics"
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
